"""Initial schema

Revision ID: e1a4510a3df7
Revises: 
Create Date: 2025-11-09 19:29:10.441293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a4510a3df7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Configuration name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Configuration description'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='True if this is the default configuration'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Configuration status'),
    sa.Column('max_turns', sa.Integer(), nullable=False, comment='Maximum conversation turns'),
    sa.Column('require_teacher_check_every', sa.Integer(), nullable=False, comment='Turns between teacher interaction reminders'),
    sa.Column('encourage_teacher_interaction', sa.Boolean(), nullable=False, comment='Enable teacher interaction prompts'),
    sa.Column('show_sources', sa.Boolean(), nullable=False, comment='Show source citations to students'),
    sa.Column('bedrock_model_id', sa.String(length=255), nullable=False, comment='Bedrock model ID to use'),
    sa.Column('bedrock_kb_id', sa.String(length=255), nullable=True, comment='Bedrock Knowledge Base ID'),
    sa.Column('temperature', sa.Float(), nullable=False, comment='Model temperature'),
    sa.Column('max_tokens', sa.Integer(), nullable=False, comment='Maximum output tokens'),
    sa.Column('top_p', sa.Float(), nullable=False, comment='Top-p sampling parameter'),
    sa.Column('system_prompt', sa.Text(), nullable=True, comment='Base system instructions'),
    sa.Column('settings', sa.JSON(), nullable=False, comment='Additional configuration settings'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was last updated'),
    sa.CheckConstraint('max_tokens > 0', name=op.f('ck_agent_configs_ck_max_tokens_positive')),
    sa.CheckConstraint('max_turns > 0', name=op.f('ck_agent_configs_ck_max_turns_positive')),
    sa.CheckConstraint('require_teacher_check_every > 0', name=op.f('ck_agent_configs_ck_teacher_check_positive')),
    sa.CheckConstraint('temperature >= 0.0 AND temperature <= 2.0', name=op.f('ck_agent_configs_ck_temperature_range')),
    sa.CheckConstraint('top_p >= 0.0 AND top_p <= 1.0', name=op.f('ck_agent_configs_ck_top_p_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_configs')),
    sa.UniqueConstraint('name', name=op.f('uq_agent_configs_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False, comment="OAuth provider's user ID"),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address'),
    sa.Column('username', sa.String(length=100), nullable=True, comment='Display username'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment="User's full name"),
    sa.Column('avatar_url', sa.String(length=512), nullable=True, comment='Profile avatar URL'),
    sa.Column('role', sa.Enum('STUDENT', 'EDUCATOR', 'ADMIN', name='userrole'), nullable=False, comment='User role in the system'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Account status'),
    sa.Column('metadata', sa.JSON(), nullable=False, comment='OAuth provider data and additional metadata'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Last login timestamp'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=True)
    op.create_table('learning_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User this profile belongs to'),
    sa.Column('learning_style', sa.Enum('VISUAL', 'AUDITORY', 'KINESTHETIC', 'READING_WRITING', 'UNKNOWN', name='learningstyle'), nullable=False, comment='Detected learning style'),
    sa.Column('learning_style_confidence', sa.Float(), nullable=False, comment='Confidence score for learning style (0.0-1.0)'),
    sa.Column('learning_style_detected_at', sa.DateTime(timezone=True), nullable=True, comment='When learning style was detected'),
    sa.Column('learning_style_indicators', sa.JSON(), nullable=False, comment='Evidence for learning style detection'),
    sa.Column('ai_summary', sa.Text(), nullable=True, comment="AI-generated analysis of student's learning patterns and orientation"),
    sa.Column('ai_summary_updated_at', sa.DateTime(timezone=True), nullable=True, comment='When AI summary was last updated'),
    sa.Column('total_sessions', sa.Integer(), nullable=False, comment='Total number of learning sessions'),
    sa.Column('total_interactions', sa.Integer(), nullable=False, comment='Total number of interactions across all sessions'),
    sa.Column('topics_studied', sa.JSON(), nullable=False, comment='List of topic IDs studied'),
    sa.Column('metadata', sa.JSON(), nullable=False, comment='Additional profile data'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft deleted (NULL = not deleted)'),
    sa.CheckConstraint('learning_style_confidence >= 0.0 AND learning_style_confidence <= 1.0', name=op.f('ck_learning_profiles_ck_learning_style_confidence_range')),
    sa.CheckConstraint('total_interactions >= 0', name=op.f('ck_learning_profiles_ck_total_interactions_positive')),
    sa.CheckConstraint('total_sessions >= 0', name=op.f('ck_learning_profiles_ck_total_sessions_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learning_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_learning_profiles_user_id'))
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Topic name'),
    sa.Column('slug', sa.String(length=255), nullable=False, comment='URL-friendly slug'),
    sa.Column('description', sa.Text(), nullable=True, comment='Topic description'),
    sa.Column('learning_objectives', sa.Text(), nullable=True, comment='Markdown-formatted learning objectives'),
    sa.Column('icon', sa.String(length=255), nullable=True, comment='Icon name or emoji'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='Parent topic for hierarchical organization'),
    sa.Column('is_global', sa.Boolean(), nullable=False, comment='True if admin-created and visible to all'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='User who created topic (NULL for global topics)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Topic activation status'),
    sa.Column('metadata', sa.JSON(), nullable=False, comment='Additional topic data'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft deleted (NULL = not deleted)'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_topics_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['topics.id'], name=op.f('fk_topics_parent_id_topics'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics')),
    sa.UniqueConstraint('name', 'created_by', name='uq_topic_name_per_user'),
    sa.UniqueConstraint('slug', 'created_by', name='uq_topic_slug_per_user')
    )
    op.create_index(op.f('ix_topics_is_global'), 'topics', ['is_global'], unique=False)
    op.create_index('ix_topics_is_global_is_active', 'topics', ['is_global', 'is_active'], unique=False)
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=False)
    op.create_index(op.f('ix_topics_slug'), 'topics', ['slug'], unique=False)
    op.create_table('knowledge_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True, comment='Related topic'),
    sa.Column('title', sa.String(length=512), nullable=False, comment='Source title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Source description'),
    sa.Column('source_type', sa.Enum('DOCUMENT', 'URL', 'TEXT', name='sourcetype'), nullable=False, comment='Type of source'),
    sa.Column('is_global', sa.Boolean(), nullable=False, comment='True if accessible to all users'),
    sa.Column('file_name', sa.String(length=255), nullable=True, comment='Original filename'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='File size in bytes'),
    sa.Column('s3_bucket', sa.String(length=255), nullable=True, comment='AWS S3 bucket name'),
    sa.Column('s3_key', sa.String(length=512), nullable=True, comment='AWS S3 object key'),
    sa.Column('partition_key', sa.String(length=255), nullable=False, comment="Partitioning key for multi-tenancy (user_<id> or 'global')"),
    sa.Column('bedrock_kb_id', sa.String(length=255), nullable=False, comment='Bedrock Knowledge Base ID'),
    sa.Column('bedrock_data_source_id', sa.String(length=255), nullable=True, comment='Bedrock Data Source ID'),
    sa.Column('vector_store_id', sa.String(length=255), nullable=True, comment='Vector store index ID (OpenSearch/Kendra)'),
    sa.Column('sync_status', sa.Enum('PENDING', 'SYNCING', 'SYNCED', 'FAILED', name='syncstatus'), nullable=False, comment='Sync status with Bedrock'),
    sa.Column('sync_error', sa.Text(), nullable=True, comment='Error message if sync failed'),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True, comment='Last successful sync timestamp'),
    sa.Column('chunk_count', sa.Integer(), nullable=False, comment='Number of chunks created'),
    sa.Column('metadata', sa.JSON(), nullable=False, comment='Additional source data (tags, author, version, etc.)'),
    sa.Column('uploaded_by', sa.Integer(), nullable=True, comment='User who uploaded the source'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft deleted (NULL = not deleted)'),
    sa.CheckConstraint('chunk_count >= 0', name=op.f('ck_knowledge_sources_ck_chunk_count_positive')),
    sa.CheckConstraint('file_size IS NULL OR file_size >= 0', name=op.f('ck_knowledge_sources_ck_file_size_positive')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_knowledge_sources_topic_id_topics'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_knowledge_sources_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_sources'))
    )
    op.create_index('ix_knowledge_bedrock_kb_ds', 'knowledge_sources', ['bedrock_kb_id', 'bedrock_data_source_id'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_bedrock_data_source_id'), 'knowledge_sources', ['bedrock_data_source_id'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_bedrock_kb_id'), 'knowledge_sources', ['bedrock_kb_id'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_is_global'), 'knowledge_sources', ['is_global'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_partition_key'), 'knowledge_sources', ['partition_key'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_sync_status'), 'knowledge_sources', ['sync_status'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_topic_id'), 'knowledge_sources', ['topic_id'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_uploaded_by'), 'knowledge_sources', ['uploaded_by'], unique=False)
    op.create_index('ix_knowledge_topic_sync', 'knowledge_sources', ['topic_id', 'sync_status'], unique=False)
    op.create_index('ix_knowledge_uploader_global', 'knowledge_sources', ['uploaded_by', 'is_global'], unique=False)
    op.create_table('learning_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Student user ID'),
    sa.Column('topic_id', sa.Integer(), nullable=True, comment='Topic being studied'),
    sa.Column('agent_config_id', sa.Integer(), nullable=True, comment='Agent configuration used for this session'),
    sa.Column('session_id', sa.String(length=255), nullable=False, comment='External session identifier'),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'PAUSED', 'ENDED', name='sessionstatus'), nullable=False, comment='Session status'),
    sa.Column('interaction_count', sa.Integer(), nullable=False, comment='Number of interactions in session'),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Session start timestamp'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True, comment='Session end timestamp'),
    sa.Column('duration_seconds', sa.Integer(), nullable=True, comment='Session duration in seconds'),
    sa.Column('detected_learning_style', sa.Enum('VISUAL', 'AUDITORY', 'KINESTHETIC', 'READING_WRITING', 'UNKNOWN', name='learningstyle'), nullable=True, comment='Learning style detected during this session'),
    sa.Column('exit_reason', sa.Enum('ACHIEVED_GOAL', 'MAX_TURNS', 'USER_EXIT', 'ERROR', 'TIMEOUT', name='exitreason'), nullable=True, comment='Reason for session exit'),
    sa.Column('metadata', sa.JSON(), nullable=False, comment='Session data (sources used, topics covered, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was last updated'),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds >= 0', name=op.f('ck_learning_sessions_ck_duration_positive')),
    sa.CheckConstraint('interaction_count >= 0', name=op.f('ck_learning_sessions_ck_interaction_count_positive')),
    sa.ForeignKeyConstraint(['agent_config_id'], ['agent_configs.id'], name=op.f('fk_learning_sessions_agent_config_id_agent_configs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_learning_sessions_topic_id_topics'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learning_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_sessions'))
    )
    op.create_index(op.f('ix_learning_sessions_agent_config_id'), 'learning_sessions', ['agent_config_id'], unique=False)
    op.create_index('ix_learning_sessions_session_created', 'learning_sessions', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_learning_sessions_session_id'), 'learning_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_learning_sessions_topic_id'), 'learning_sessions', ['topic_id'], unique=False)
    op.create_index('ix_learning_sessions_topic_status', 'learning_sessions', ['topic_id', 'status'], unique=False)
    op.create_index(op.f('ix_learning_sessions_user_id'), 'learning_sessions', ['user_id'], unique=False)
    op.create_index('ix_learning_sessions_user_status', 'learning_sessions', ['user_id', 'status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='Parent session ID'),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False, comment='Message role'),
    sa.Column('content', sa.Text(), nullable=False, comment='Message content'),
    sa.Column('bedrock_invocation_id', sa.String(length=255), nullable=True, comment='Bedrock request ID'),
    sa.Column('model_used', sa.String(length=100), nullable=True, comment='Which Bedrock model was used'),
    sa.Column('input_tokens', sa.Integer(), nullable=True, comment='Input token count'),
    sa.Column('output_tokens', sa.Integer(), nullable=True, comment='Output token count'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='Response latency in milliseconds'),
    sa.Column('metadata', sa.JSON(), nullable=False, comment='Message metadata (sources, citations, tool calls)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Message timestamp'),
    sa.CheckConstraint('input_tokens IS NULL OR input_tokens >= 0', name=op.f('ck_messages_ck_input_tokens_positive')),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name=op.f('ck_messages_ck_latency_positive')),
    sa.CheckConstraint('output_tokens IS NULL OR output_tokens >= 0', name=op.f('ck_messages_ck_output_tokens_positive')),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], name=op.f('fk_messages_session_id_learning_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_bedrock_invocation_id'), 'messages', ['bedrock_invocation_id'], unique=False)
    op.create_index('ix_messages_session_created', 'messages', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_table('session_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='Parent session ID'),
    sa.Column('state_data', sa.JSON(), nullable=False, comment='Agent state JSON blob (memory, context, planning)'),
    sa.Column('state_summary', sa.Text(), nullable=True, comment='Summarized state generated every 5 turns'),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], name=op.f('fk_session_states_session_id_learning_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_states')),
    sa.UniqueConstraint('session_id', name=op.f('uq_session_states_session_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_states')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_index('ix_messages_session_created', table_name='messages')
    op.drop_index(op.f('ix_messages_bedrock_invocation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_learning_sessions_user_status', table_name='learning_sessions')
    op.drop_index(op.f('ix_learning_sessions_user_id'), table_name='learning_sessions')
    op.drop_index('ix_learning_sessions_topic_status', table_name='learning_sessions')
    op.drop_index(op.f('ix_learning_sessions_topic_id'), table_name='learning_sessions')
    op.drop_index(op.f('ix_learning_sessions_session_id'), table_name='learning_sessions')
    op.drop_index('ix_learning_sessions_session_created', table_name='learning_sessions')
    op.drop_index(op.f('ix_learning_sessions_agent_config_id'), table_name='learning_sessions')
    op.drop_table('learning_sessions')
    op.drop_index('ix_knowledge_uploader_global', table_name='knowledge_sources')
    op.drop_index('ix_knowledge_topic_sync', table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_uploaded_by'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_topic_id'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_sync_status'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_partition_key'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_is_global'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_bedrock_kb_id'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_bedrock_data_source_id'), table_name='knowledge_sources')
    op.drop_index('ix_knowledge_bedrock_kb_ds', table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    op.drop_index(op.f('ix_topics_slug'), table_name='topics')
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.drop_index('ix_topics_is_global_is_active', table_name='topics')
    op.drop_index(op.f('ix_topics_is_global'), table_name='topics')
    op.drop_table('topics')
    op.drop_table('learning_profiles')
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('agent_configs')
    # ### end Alembic commands ###